config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :works

  resources :vendors

end

app/models/service.rb
class Service < ActiveRecord::Base
	has_and_belongs_to_many :vendors
	has_and_belongs_to_many :works
end

app/models/technology.rb
class Technology < ActiveRecord::Base
	has_and_belongs_to_many :vendors
end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	belongs_to :vendors
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_many :works
	has_and_belongs_to_many :technologies
	has_and_belongs_to_many :services
	has_many :testimonials
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :vendor
	has_and_belongs_to_many :services
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		Rails.logger.info "*******************************"
		Rails.logger.info "Enterprise"
		Rails.logger.info "*******************************"
		@vendor_list_for_enterprise = get_vendor_list("Enterprise")
		Rails.logger.info "*******************************"
		Rails.logger.info "B2B"
		Rails.logger.info "*******************************"

		@vendor_list_for_b2b =  get_vendor_list("B2B")
		Rails.logger.info @vendor_list_for_enterprise
		Rails.logger.info @vendor_list_for_b2b
	end

	private

	def get_vendor_list(word_to_search)
		vendor = Hash.new
		Vendor.all.each do |v|
			testi_word_count = 0
			service_word_count = 0
			title_word_count = 0
			v.testimonials.each do |testi|
				testi_word_count += testi.content.scan(/#{word_to_search}/i).count
				Rails.logger.info "*******************************"
				Rails.logger.info "testi_word_count"
				Rails.logger.info testi_word_count
				Rails.logger.info "*******************************"
			end
			v.services.each do |service|
				service_word_count += service.name.scan(/#{word_to_search}/i).count
				Rails.logger.info "*******************************"
				Rails.logger.info "service_word_count"
				Rails.logger.info service_word_count
				Rails.logger.info "*******************************"
			end
			v.works.each do |work|
				title_word_count += work.title.scan(/#{word_to_search}/i).count
				Rails.logger.info "*******************************"
				Rails.logger.info "title_word_count"
				Rails.logger.info title_word_count
				Rails.logger.info "*******************************"
			end
			sum_of_counts = testi_word_count + service_word_count + title_word_count
			Rails.logger.info "*******************************"
			Rails.logger.info "sum_of_counts"
			Rails.logger.info sum_of_counts
			Rails.logger.info "*******************************"
			if sum_of_counts!=0
				vendor[v] = sum_of_counts
			end
		end
		Hash[vendor.sort_by{|k, v| [v,k.works.sum(:number_of_views)] }.reverse].keys.take(4)
	end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:vendor_id, :screen_shot, :url, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/home/index.html.erb
<div class="container">
	<div class="row">
		<legend class="text-center">Listing vendors based on the precense of the frequency of the word Enterprise </legend>	
		<% @vendor_list_for_enterprise.each do |vendor|%>
		<% if not vendor.works.empty?%>
		<div class="span3">
			<div class="well well-sm">
				<%= image_tag "http://upload.wikimedia.org/wikipedia/commons/f/f6/Random_sky.jpg" %>
				<span class="glyphicon glyphicon-picture"></span><%= vendor.works.first.title %>
				<br/>
				by <%= vendor.company %>
				<hr class="micro">
				Technology Used: <%= vendor.works.first.services.map{|n| n.name.humanize}.join(",")%>
				<div class="foot-strip">
				Number of Views:	<%= vendor.works.first.number_of_views%>
				</div>
			</div>
		</div>
		<% end %>
		<% end %>
	</div>
</div>
<div class="container">
	<div class="row">
		<legend class="text-center">Listing vendors based on the precense of the frequency of the word B2B </legend>	
		<% @vendor_list_for_b2b.each do |vendor|%>
		<% if not vendor.works.empty?%>
		<div class="span3">
			<div class="well well-sm">
				<%= image_tag "http://upload.wikimedia.org/wikipedia/commons/f/f6/Random_sky.jpg" %>
				<span class="glyphicon glyphicon-picture"></span><%= vendor.works.first.title %>
				<br/>
				by <%= vendor.company %>
				<hr class="micro">
				Technology Used: <%= vendor.works.first.services.map{|n| n.name.humanize}.join(",")%>
				<div class="foot-strip">
				Number of Views:	<%= vendor.works.first.number_of_views%>
				</div>

			</div>
		</div>
		<% end %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contractiq</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :no_of_employees %><br>
    <%= f.number_field :no_of_employees %>
  </div>
  <div class="field">
    <%= f.label :year_of_founding %><br>
    <%= f.number_field :year_of_founding %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :git_link %><br>
    <%= f.text_field :git_link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1>Listing vendors</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Website</th>
      <th>No of employees</th>
      <th>Year of founding</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Display name</th>
      <th>Phone</th>
      <th>Logo</th>
      <th>Git link</th>
      <th>Works</th>
      <th>Services</th>
      <th>Testimonials</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.company %></td>
        <td><%= vendor.website %></td>
        <td><%= vendor.no_of_employees %></td>
        <td><%= vendor.year_of_founding %></td>
        <td><%= vendor.first_name %></td>
        <td><%= vendor.last_name %></td>
        <td><%= vendor.display_name %></td>
        <td><%= vendor.phone %></td>
        <td><%= vendor.logo %></td>
        <td><%= vendor.git_link %></td>
        <td><%= vendor.works.inspect %></td>
        <td><%= vendor.services.inspect %></td>
        <td><%= vendor.testimonials.inspect %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @vendor.company %>
</p>

<p>
  <strong>Website:</strong>
  <%= @vendor.website %>
</p>

<p>
  <strong>No of employees:</strong>
  <%= @vendor.no_of_employees %>
</p>

<p>
  <strong>Year of founding:</strong>
  <%= @vendor.year_of_founding %>
</p>

<p>
  <strong>First name:</strong>
  <%= @vendor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @vendor.last_name %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @vendor.display_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vendor.phone %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @vendor.logo %>
</p>

<p>
  <strong>Git link:</strong>
  <%= @vendor.git_link %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vendor_id %><br>
    <%= f.text_field :vendor_id %>
  </div>
  <div class="field">
    <%= f.label :screen_shot %><br>
    <%= f.text_field :screen_shot %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<h1>Listing works</h1>

<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Screen shot</th>
      <th>Url</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.vendor %></td>
        <td><%= work.screen_shot %></td>
        <td><%= work.url %></td>
        <td><%= work.title %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendor:</strong>
  <%= @work.vendor %>
</p>

<p>
  <strong>Screen shot:</strong>
  <%= @work.screen_shot %>
</p>

<p>
  <strong>Url:</strong>
  <%= @work.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @work.title %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>